name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: SamilMoret
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Upload Snake GIF
        uses: actions/upload-artifact@v2
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.gif

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
          allow_empty_commit: true
          jekyll: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN 
