name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: SamilMoret  
          gif_out_path: dist/github-contribution-grid-snake.gif

      - uses: actions/upload-artifact@v2
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.gif
